language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

script:
    - go test -v -parallel=8 -cover -coverprofile=profile.out
    - $HOME/gopath/bin/goveralls -coverprofile=profile.out -repotoken TrwPM1p2YUjRXZx6cdSmjWHo9WOZBFoLY
